### ISSUE TITLE
API responding 200 on error

### ISSUE THREAD

**Issue by mholcombengi** [engi-network/engi-blockchain-gql#182]
Observed 200 responses when enrolling fails.  

Example log:

```
Request starting HTTP/1.1 POST http://graphql:5000/api/graphql application/json 303
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Executing endpoint 'GraphQL'
info: Microsoft.AspNetCore.Session.DistributedSession[2]
Accessing expired session, Key:a4ab3d12-e531-e690-009d-25bdc7e4e45f
info: Engi.Substrate.Server.Types.Github.GithubMutations[0]
Enrolling installation 44801263
fail: Engi.Substrate.Server.RootSchema[0]
Error occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Engi.Substrate.Server.Types.Github.GithubMutations.EnrollAsync(IResolveFieldContext`1 context) in /source/engi-server/Types/Github/GithubMutations.cs:line 63
at Engi.Substrate.Server.Types.Github.GithubMutations.EnrollAsync(IResolveFieldContext`1 context) in /source/engi-server/Types/Github/GithubMutations.cs:line 111
at Engi.Substrate.Server.Types.Validation.ValidationMiddleware.ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next) in /source/engi-server/Types/Validation/ValidationMiddleware.cs:line 22
at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 502
info: Sentry.ISentryClient[0]
Capturing event.
info: Sentry.ISentryClient[0]
Envelope queued up: '0e959c971caa4f899a0e2be24a5961fa'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed endpoint 'GraphQL'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Request finished HTTP/1.1 POST http://graphql:5000/api/graphql application/json 303 - 200 - application/json;+charset=utf-8 243.5600ms
```

**Comment by garrettmaring** [comment]
this will help us filter out 200 logging more aggressively
